_target_: ligthning.pytorch.strategies.DeepSpeedStrategy

# ZeRO optimization
zero_optimization: True
stage: 2
offload_optimizer: True
offload_optimizer_device: "cpu"
contiguous_gradients: True

# Activation Checkpointing
partition_activations: False
cpu_checkpointing: False
