_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 100

accelerator: gpu
devices: 1

# mixed precision for extra speed-up
precision: 'bf16-mixed' # '16-true', '16-mixed', 'bf16-true', '32-true',

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# frequency of logging
log_every_n_steps: 10

# gradient clipping
gradient_clip_val: 10.0  # gradient clipping if global norm is greater than 10

# How much of training/test/validation dataset to check.
# Useful when debugging or testing something that happens at the end of an epoch
limit_train_batches: 1.0
limit_test_batches: 1.0
limit_val_batches: 1.0

# use only 1% of the train & val set
# overfit_batches: 0.01

# Profiler choose between "simple", "advanced"
profiler: "simple"  # None

# Detect autograd anomalies. This will significantly slow down compute speed, useful for debugging
detect_anomaly: false

enable_progress_bar: null

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
