# _target_: # the loss object maybe?

diffusion_loss:
    mse:
        weight_dna: 5.0
        weight_rna: 5.0
        weight_ligand: 10.0
        weight_protein: 1.0
    smooth_lddt:
        weight: 1.0

distogram:
    min_bin: 2.3125
    max_bin: 21.6875
    no_bins: 64,
    eps: 0.000006  # 1e-6
    weight: 0.3

experimentally_resolved:
    eps: 0.00000008,  # 1e-8,
    min_resolution: 0.1,
    max_resolution: 3.0,
    weight: 0.0,

plddt_loss:
    min_resolution: 0.1,
    max_resolution: 3.0,
    cutoff: 15.0,
    no_bins": 50,
    eps: 0.0000000001,  # 1e-10,
    weight: 0.01,

# Integration weights of all the losses
loss_weights:
    diffusion: 4.0
    distogram: 0.03
    pae: 0.0
    confidence: 0.0004
