# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries
name: alphafold

channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - adaptyvbio
  - defaults

dependencies:
  - python=3.10
  - packaging>=23.2,<24.0
  - absl-py
  - pip

  # --------- pytorch --------- #
  - pytorch=2.4.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4  # for CUDA version 12.4
  - pytorch-lightning

  # --------- kernels --------- #
  - einops

  # --------- loggers --------- #
  - wandb

  # --------- others --------- #
  - pre-commit
  - rich
  - pytest
  - pandas
  - p-tqdm
  - proteinflow==2.7.0
  - biopython
  - setuptools>=68.2.2,<68.3.0
  - tqdm
  - pandas
  - pip:
      - deepspeed==0.14.4
      - dm-tree>=0.1.8,<0.2.0
      - torchmetrics
      # --------- hydra --------- #
      - hydra-core>=1.3,<0.1.4.0
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils>=1.0.7,<1.1.0
      - ml_collections
