# AlphaFold3 loss configs
mse_loss:
  sd_data: 16.0
  weight: 4.0
smooth_lddt_loss:
  weight: 4.0
  epsilon: 1e-5

distogram:
    min_bin: 0.0
    max_bin: 32.0
    no_bins: 64
    eps: 1e-6
    weight: 0.03

experimentally_resolved:
    eps: 1e-8
    # min_resolution: 0.1,
    # max_resolution: 3.0,
    weight: 4e-4

plddt_loss:
    min_resolution: 0.1
    max_resolution: 3.0
    cutoff: 15.0
    no_bins": 50
    eps: 1e-10
    weight: 4e-4