# _target_: # TODO: fill in this file with AF3 model config

# Common model parameters like c_s, c_z, etc. used across multiple modules
common:
  c_token: 384  # the token representation dim
  c_pair: 128  # the pair representation dim
  c_atom: 128  # the atom representation dim
  c_atompair: 16  # the atom pair representation dim

# Input Embedder
input_embedder:
  c_token: ${common.c_token}
  c_pair: ${common.c_pair}
  c_atom: ${common.c_atom}
  c_atompair: ${common.c_atompair}

# PairformerStack
pairformer_stack:
  c_s: ${common.c_token}
  c_z: ${common.c_pair}
  no_blocks: 48
  c_hidden_mul: 128
  c_hidden_pair_att: 32
  no_heads_pair: 4
  no_heads_single_att: 16
  transition_n: 4
  pair_dropout: 0.25
  fuse_projection_weights: False
  blocks_per_ckpt: 1
  clear_cache_between_blocks: False
  inf: 1e8

# Diffusion module
diffusion_module:
  c_atom: ${common.c_atom}
  c_atompair: ${common.c_atompair}
  c_token: ${common.c_token}
  c_tokenpair: ${common.c_pair}
  atom_encoder_blocks: 3
  atom_encoder_heads: 16
  dropout: 0.0
  atom_attention_n_queries: 32  # TODO: with sliding window attention this is not used.
  atom_attention_n_keys: 128
  atom_decoder_blocks: 3
  atom_decoder_heads: 16
  token_transformer_blocks: 24
  token_transformer_heads: 16
  sd_data: 16.0
  s_max: 160.0
  s_min: 4e-4
  p: 7.0
  clear_cache_between_blocks: False
  blocks_per_ckpt: 1
  compile_model: False  # TODO: this parameter does not belong here, will be removed in future iterations.

confidence_head:
  c_s: ${common.c_token}
  c_z: ${common.c_pair}
  no_blocks: 4
  no_bins_pde: 64
  no_bins_plddt: 64
  no_bins_pae: 64

distogram_head:
  c_z: ${common.c_pair}
  no_bins: 64
