_target_: src.models.kestrel_module.KestrelLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-5
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

structure_module:
  _target_: src.models.structure_module.StructureModule
  c_s: 128
  c_z: 128
  c_ipa: 16
  no_heads_ipa: 12
  no_qk_points: 4
  no_v_points: 8
  dropout_rate: 0.1
  no_blocks: 8
  no_transition_layers: 1
  epsilon: 1e-6
  inf: 1e8

evoformer:
  _target_: src.models.evoformer.EvoformerStack
  n_blocks: 1
  c_s: 128
  c_z: 128
  n_msa_row_attention_heads: 8
  c_hidden_msa_per_head: 32
  c_hidden_outer: 32
  c_hidden_tri_mul: 128
  n_triangle_attention_heads: 4
  c_hidden_tri_att_per_head: 32
  dropout_msa: 0.15
  dropout_pair: 0.25

feature_net:
  _target_: src.models.feature_net.FeatureNet
  c_z: 128
  c_s: 128
  c_ipa: 16
  no_heads_ipa: 12
  no_qk_points: 4
  no_v_points: 8
  relpos_k: 32

# compile model for faster training with pytorch 2.0
compile: false