# Mini AlphaFold3 configs
defaults:
  - /model/alphafold3
  - /loss/alphafold3_loss
  - /scheduler/alphafold3_lr

model:
  c_token: 128  # Reduced from 384
  
  pairformer_stack:
    no_blocks: 12  # Reduced from 48

  diffusion_module:
    token_transformer_blocks: 6  # Reduced from 24
