# AlphaFold3 configs
defaults:
  - optimizer: fused_adam
  - scheduler: alphafold3_lr
  - loss: no_smooth_lddt
  - _self_
  - alphafold3

pairformer_stack:
  no_blocks: 24

diffusion_module:
  token_transformer_blocks: 12
